# Generated by Django 4.2 on 2023-04-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_favorites_alter_movie_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='likes',
        ),
    ]
