# Generated by Django 4.2 on 2023-04-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_movie_likes'),
        ('account', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_movies',
            field=models.ManyToManyField(related_name='favorited_by', to='movie.movie'),
        ),
    ]
