# Generated by Django 4.2 on 2023-04-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_remove_movie_favorites_remove_movie_likes'),
        ('account', '0005_remove_customuser_favorite_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_movies',
            field=models.ManyToManyField(related_name='favorited_by', to='movie.movie'),
        ),
    ]
