# Generated by Django 4.2 on 2023-04-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_movie_likes'),
        ('account', '0007_customuser_likes_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='likes_movies',
            field=models.ManyToManyField(blank=True, related_name='likes_by', to='movie.movie'),
        ),
    ]
